config/routes.rb
Rails.application.routes.draw do
  mount Lookbook::Engine, at: '/lookbook' if Rails.env.development?

  get 'support', to: 'pages#support', as: :support
  root 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end

  def support; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heroicon_helper.rb
# frozen_string_literal: true

module HeroiconHelper
  include Heroicon::Engine.helpers
end

app/views/layouts/_sidebar.html.slim
nav id='sidebar' class='w-[300px] flex flex-col gap-2 h-full fixed top-0 left-[-300px] lg:left-0 lg:static bg-white border-r border-gray-200 rounded-r-xl'
  header class='flex-1 overflow-hidden px-2 py-4'
    div class='pb-4 flex items-center'
      = heroicon 'arrow-path-rounded-square', options:{class: 'w-5 h-5 inline mr-2'}
      h1 class='text-2xl font-semibold flex items-center tracking-wider text-gray-800 flex-1'
        span di
        span class='w-6 h-6 bg-sky-400 pl-0.5 mx-0.5 text-white text-lg font-bold rounded-tr-md rounded-bl-md flex items-center justify-center' P
        span az
      div data-controller='sidebar' class='block lg:hidden'
        button data-action='click->sidebar#showSidebar'
          = heroicon 'x-mark', options:{class: 'w-5 h-5 inline'}
    hr class='mb-4'
    div class='menu h-full overflow-y-auto text-sm font-medium text-gray-800'
      ul class='space-y-1' data-controller='sidebar'
        li
          = render MenuLinkComponent.new(href: root_path,
          icon: heroicon('home', variant: :solid, options:{class: 'w-5 h-5 inline'}),
          title: 'Home')
        li
          = render MenuLinkComponent.new(href: root_path,
          icon: heroicon('bell', variant: :solid, options:{class: 'w-5 h-5 inline'}),
          title: 'Notifications')

        li class='sidebar-btn cursor-pointer' data-action='click->sidebar#toggleSubmenu'
          h4 class='pointer-events-none flex justify-between items-center w-full text-sky-600'
            div class='flex items-center gap-2'
              = heroicon 'user-group', variant: :solid, options:{class: 'w-5 h-5 inline' }
              span Customers
            div
              = heroicon 'ellipsis-vertical', variant: :solid, options:{class: 'w-5 h-5 inline' }

        li id='customer-submenu' class=''
          div class='ml-4 pl-2 border-l border-gray-200'
            ul class='space-y-1'
              li
                = render MenuLinkComponent.new(href: root_path,
                  icon: heroicon('user-plus', variant: :solid, options:{class: 'w-5 h-5 inline'}),
                  title: 'New Customer')
              li
                = render MenuLinkComponent.new(href: root_path,
                  icon: heroicon('banknotes', variant: :solid, options:{class: 'w-5 h-5 inline'}),
                  title: 'Payment')
              li
                = render MenuLinkComponent.new(href: root_path,
                  icon: heroicon('chart-pie', variant: :solid, options:{class: 'w-5 h-5 inline'}),
                  title: 'Charts')
              li
                = render MenuLinkComponent.new(href: root_path,
                  icon: heroicon('list-bullet', variant: :solid, options:{class: 'w-5 h-5 inline'}),
                  title: 'List Customers')

        li class='sidebar-btn cursor-pointer' data-action='click->sidebar#toggleSubmenu'
          h4 class='pointer-events-none flex justify-between items-center w-full text-sky-600'
            div class='flex items-center gap-2'
              = heroicon 'wallet', variant: :solid, options:{class: 'w-5 h-5 inline' }
              span Company
            div
              = heroicon 'ellipsis-vertical', variant: :solid, options:{class: 'w-5 h-5 inline' }

        li id='company-submenu' class=''
          div class='ml-4 pl-2 border-l border-gray-200'
            ul class='space-y-1'
              li
                = render MenuLinkComponent.new(href: root_path,
                  icon: heroicon('finger-print', variant: :solid, options:{class: 'w-5 h-5 inline'}),
                  title: 'Register')
              li
                = render MenuLinkComponent.new(href: root_path,
                  icon: heroicon('device-phone-mobile', variant: :solid, options:{class: 'w-5 h-5 inline'}),
                  title: 'Contacts')
              li
                = link_to root_path, class: 'sidebar-btn' do
                  div class='flex items-center gap-2'
                    = heroicon 'arrow-down-on-square', variant: :solid, options:{class: 'w-5 h-5 inline' }
                    span Plans

        li class='sidebar-btn cursor-pointer pointer-events-none md:pointer-events-auto' data-action='click->sidebar#toggleSubmenu'
          h4 class='pointer-events-none flex justify-between items-center w-full text-sky-600'
            div class='flex items-center gap-2'
              = heroicon 'server-stack', variant: :solid, options:{class: 'w-5 h-5 inline' }
              span Workflow
            div
              = heroicon 'ellipsis-vertical', variant: :solid, options:{class: 'w-5 h-5 inline' }

        li id='workflow-submenu' class=''
          div class='ml-4 pl-2 border-l border-gray-200'
            ul class='space-y-1'
              li
                = render MenuLinkComponent.new(href: root_path,
                  icon: heroicon('calendar-days', variant: :solid, options:{class: 'w-5 h-5 inline'}),
                  title: 'Tasks')
              li
                = render MenuLinkComponent.new(href: root_path,
                  icon: heroicon('calculator', variant: :solid, options:{class: 'w-5 h-5 inline'}),
                  title: 'Billing')
              li
                = render MenuLinkComponent.new(href: root_path,
                  icon: heroicon('chart-bar', variant: :solid, options:{class: 'w-5 h-5 inline'}),
                  title: 'Metrics')
              li
                = render MenuLinkComponent.new(href: root_path,
                  icon: heroicon('cog', variant: :solid, options:{class: 'w-5 h-5 inline'}),
                  title: 'Setting')
              li
                = render MenuLinkComponent.new(href: support_path,
                  icon: heroicon('chat-bubble-left-right', variant: :solid, options:{class: 'w-5 h-5 inline'}),
                  title: 'Support', action: :support)
  footer class='px-2 pb-4'
    hr class='mb-4'
    div class='flex items-center gap-2'
      div
        = render AvatarComponent.new(image: 'https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fimages.unsplash.com%2Fphoto-1610043809095-9c87fe936e03%3Fixlib%3Drb-1.2.1%26q%3D80%26fm%3Djpg%26crop%3Dentropy%26cs%3Dtinysrgb%26w%3D1080%26fit%3Dmax&f=1&nofb=1&ipt=9fe4894c9773579669ab981aa7f81b63ccacd5af543049341dac46d5d2d21b02&ipo=images', size: 'w-11 h-11', custom_class:'rounded-lg')

      div class='flex-1 overflow-hidden'
        span class='text-sm font-medium text-gray-800' John Doe
      div class='text-right'
        = link_to '#', class: 'hover:text-sky-600' do
          = heroicon 'arrow-right-on-rectangle', variant: :outline, options:{class: 'w-5 h-5 inline' }

app/views/layouts/application.html.slim
doctype html
html
  head
    title w3n templates
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"

    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags

  body class='bg-gray-100'
    main class='flex w-full h-screen gap-0.5'
      aside id='aside-menu' class='h-full relative z-50 md:w-auto md:flex-shrink-0'
        div data-controller='sidebar' class='block lg:hidden'
          button id='show-sidebar' class='absolute top-2 left-4' data-action='click->sidebar#showSidebar'
            div class='cursor-pointer bg-sky-400 flex justify-center items-center p-2 text-white rounded hover:bg-sky-500 pointer-events-none'
              = heroicon 'bars-3-center-left', options:{class: 'w-5 h-5 inline'}
        = render 'layouts/sidebar'
      section class='flex-1 bg-white rounded-xl'
        div id='bk-menu' class='hidden'
          div class='absolute top-0 right-0 bottom-0 left-0 z-10 bg-black/20'
        = yield

app/views/pages/home.html.slim
h1 Pages#home
p Find me in app/views/pages/home.html.slim

app/views/pages/support.html.slim
h1 class='text-2xl font-bold' Support